// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdEFy5G2sANlTYbjP24xMky9upsYqUWZk',
    appId: '1:642774363823:web:40bc5a4f5c732738d92e5a',
    messagingSenderId: '642774363823',
    projectId: 'easytrip-fedc9',
    authDomain: 'easytrip-fedc9.firebaseapp.com',
    storageBucket: 'easytrip-fedc9.firebasestorage.app',
    measurementId: 'G-CKV4SFESJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7VYF1RTGcT7ET39Bc51Rbf_axCjGGJmo',
    appId: '1:642774363823:android:853bd5b50cf4ad1fd92e5a',
    messagingSenderId: '642774363823',
    projectId: 'easytrip-fedc9',
    storageBucket: 'easytrip-fedc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1XSTYkzLeswwJOxWphZ8Jpx9ZA_Cmw-g',
    appId: '1:642774363823:ios:3c9d2b84ef32e321d92e5a',
    messagingSenderId: '642774363823',
    projectId: 'easytrip-fedc9',
    storageBucket: 'easytrip-fedc9.firebasestorage.app',
    iosBundleId: 'com.example.easyTripAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1XSTYkzLeswwJOxWphZ8Jpx9ZA_Cmw-g',
    appId: '1:642774363823:ios:3c9d2b84ef32e321d92e5a',
    messagingSenderId: '642774363823',
    projectId: 'easytrip-fedc9',
    storageBucket: 'easytrip-fedc9.firebasestorage.app',
    iosBundleId: 'com.example.easyTripAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdEFy5G2sANlTYbjP24xMky9upsYqUWZk',
    appId: '1:642774363823:web:d1e5ba88644d0b9ed92e5a',
    messagingSenderId: '642774363823',
    projectId: 'easytrip-fedc9',
    authDomain: 'easytrip-fedc9.firebaseapp.com',
    storageBucket: 'easytrip-fedc9.firebasestorage.app',
    measurementId: 'G-CF8EV0MEKL',
  );
}
